echo Downloading the 21 subtraces of FIU Traces
setlocal
set cookies=%TEMP%\iotta_cookies.txt
set token=%TEMP%\iotta_wget_remember_token.txt

echo # Netscape HTTP Cookie File > %cookies%
echo # http://curl.haxx.se/rfc/cookie_spec.html>> %cookies%
echo # This script must be run using the same IP adress with which it was downloaded>> %cookies%
echo # This file was generated by iotta.snia.org! Edit at your own risk.>> %cookies%
echo>> %cookies%
echo .iotta.snia.org	TRUE	/	FALSE	0	infodigest	c62bc27954a7a0e25d1613651c147de0d2eaaeeb>> %cookies%
echo .iotta.snia.org	TRUE	/	FALSE	0	legal	true>> %cookies%
echo .iotta.snia.org	TRUE	/	FALSE	0	id	523032>> %cookies%

if exist "C:\Program Files (x86)\GnuWin32\bin\wget.exe" (
  echo Found Default Path
  set wget="C:\Program Files (x86)\GnuWin32\bin\wget.exe"
  goto :download
) else if exist %token% (
  echo Old token for wget is found
  goto :found_token
) else (
  echo Please wait while the system locates wget
  goto :not_found_token
)

:not_found_token
  dir c:\wget.exe /a:-d /b /s > %token%
:found_token
  set /p wget=<%token%
  set wget="%wget%"
  if %wget%=="" (
    echo wget file not found. Please install wget.
    goto :eof
  )
  echo wget=%wget%
:download

%wget%   --load-cookies=%cookies% -O "mail-01.tar.gz" -c "http://server3.iotta.snia.org/traces/392/download?type=file&sType=bwget" || exit /b

%wget%   --load-cookies=%cookies% -O "mail-02.tar.gz" -c "http://server3.iotta.snia.org/traces/393/download?type=file&sType=bwget" || exit /b

%wget%   --load-cookies=%cookies% -O "mail-03.tar.gz" -c "http://server3.iotta.snia.org/traces/394/download?type=file&sType=bwget" || exit /b

%wget%   --load-cookies=%cookies% -O "mail-04.tar.gz" -c "http://server3.iotta.snia.org/traces/395/download?type=file&sType=bwget" || exit /b

%wget%   --load-cookies=%cookies% -O "mail-05.tar.gz" -c "http://server3.iotta.snia.org/traces/396/download?type=file&sType=bwget" || exit /b

%wget%   --load-cookies=%cookies% -O "mail-06.tar.gz" -c "http://server3.iotta.snia.org/traces/397/download?type=file&sType=bwget" || exit /b

%wget%   --load-cookies=%cookies% -O "mail-07.tar.gz" -c "http://server3.iotta.snia.org/traces/398/download?type=file&sType=bwget" || exit /b

%wget%   --load-cookies=%cookies% -O "mail-08.tar.gz" -c "http://server3.iotta.snia.org/traces/399/download?type=file&sType=bwget" || exit /b

%wget%   --load-cookies=%cookies% -O "mail-09.tar.gz" -c "http://server3.iotta.snia.org/traces/400/download?type=file&sType=bwget" || exit /b

%wget%   --load-cookies=%cookies% -O "mail-10.tar.gz" -c "http://server3.iotta.snia.org/traces/401/download?type=file&sType=bwget" || exit /b

%wget%   --load-cookies=%cookies% -O "homes.tar.gz" -c "http://server3.iotta.snia.org/traces/402/download?type=file&sType=bwget" || exit /b

%wget%   --load-cookies=%cookies% -O "web-vm.tar.gz" -c "http://server3.iotta.snia.org/traces/403/download?type=file&sType=bwget" || exit /b

%wget%   --load-cookies=%cookies% -O "home1.tar.gz" -c "http://server3.iotta.snia.org/traces/405/download?type=file&sType=bwget" || exit /b

%wget%   --load-cookies=%cookies% -O "home2.tar.gz" -c "http://server3.iotta.snia.org/traces/406/download?type=file&sType=bwget" || exit /b

%wget%   --load-cookies=%cookies% -O "home3.tar.gz" -c "http://server3.iotta.snia.org/traces/407/download?type=file&sType=bwget" || exit /b

%wget%   --load-cookies=%cookies% -O "mail.tar.gz" -c "http://server3.iotta.snia.org/traces/408/download?type=file&sType=bwget" || exit /b

%wget%   --load-cookies=%cookies% -O "online.tar.gz" -c "http://server3.iotta.snia.org/traces/409/download?type=file&sType=bwget" || exit /b

%wget%   --load-cookies=%cookies% -O "webmail.tar.gz" -c "http://server3.iotta.snia.org/traces/410/download?type=file&sType=bwget" || exit /b

%wget%   --load-cookies=%cookies% -O "webresearch.tar.gz" -c "http://server3.iotta.snia.org/traces/411/download?type=file&sType=bwget" || exit /b

%wget%   --load-cookies=%cookies% -O "webusers.tar.gz" -c "http://server3.iotta.snia.org/traces/412/download?type=file&sType=bwget" || exit /b

%wget%   --load-cookies=%cookies% -O "home4.tar.gz" -c "http://server3.iotta.snia.org/traces/413/download?type=file&sType=bwget" || exit /b

del %cookies%
